### ISSUE TITLE
Empty transform being published

### ISSUE THREAD

**Issue by smits** [Intermodalics/tango_ros#157]
RVIZ spits out the following error message continuously: `[ERROR] [1487241456.113933219]: Ignoring transform from authority "unknown_publisher" because child_frame_id not set 
[ERROR] [1487241456.113974897]: Ignoring transform with child_frame_id ""  from authority "unknown_publisher" because frame_id not set`

rostopic echo /tf shows an empty tf frame being published which causes this:
```
transforms: 
  - 
    header: 
      seq: 0
      stamp: 
        secs: 0
        nsecs:         0
      frame_id: ''
    child_frame_id: ''
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 0.0
---
```
