### ISSUE TITLE
Crash when reconnecting to Tango (Lenovo phone)

### ISSUE THREAD

**Issue by PerrineAguiar** [Intermodalics/tango_ros#353]
Could be related to the crash on YS device (#219).

**Comment by PerrineAguiar** [comment]
Could be related to this crash reported on GooglePlay Console
```
backtrace:
  native: pc 0000000000044320  /system/lib/libc.so (tgkill+12)
  native: pc 0000000000041f21  /system/lib/libc.so (pthread_kill+32)
  native: pc 000000000001ba4f  /system/lib/libc.so (raise+10)
  native: pc 0000000000018bf1  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 00000000000167b0  /system/lib/libc.so (abort+4)
  native: pc 00000000005402eb  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN9__gnu_cxx27__verbose_terminate_handlerEv+226)
  native: pc 0000000000509121  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN10__cxxabiv111__terminateEPFvvE+4)
  native: pc 0000000000509195  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZSt9terminatev+8)
  native: pc 00000000001e2ac7  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN16tango_ros_native12TangoRosNode15StartPublishingEv+462)
  native: pc 00000000001f1f6d  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN16tango_ros_native12TangoRosNode26ConnectToTangoAndSetUpNodeEv+128)
  native: pc 00000000001f20df  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN16tango_ros_native12TangoRosNode27TangoConnectServiceCallbackERKN18tango_ros_messages20TangoConnectRequest_ISaIvEEERNS1_21TangoConnectResponse_IS3_EE+186)
  native: pc 00000000001ea44b  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN3ros22ServiceCallbackHelperTINS_11ServiceSpecIN18tango_ros_messages20TangoConnectRequest_ISaIvEEENS2_21TangoConnectResponse_IS4_EEEEE4callERNS_31ServiceCallbackHelperCallParamsE+214)
  native: pc 0000000000258a25  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN3ros15ServiceCallback4callEv+308)
  native: pc 00000000002742ad  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN3ros13CallbackQueue9callOneCBEPNS0_3TLSE+296)
  native: pc 0000000000274455  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN3ros13CallbackQueue7callOneENS_12WallDurationE+196)
  native: pc 00000000002b5c67  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN7nodelet6detail13CallbackQueue7callOneEv+170)
  native: pc 00000000002b6e79  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN7nodelet6detail20CallbackQueueManager12workerThreadEPNS1_10ThreadInfoE+128)
  native: pc 00000000002b5db5  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so (_ZN5boost6detail11thread_dataINS_3_bi6bind_tIvNS_4_mfi3mf1IvN7nodelet6detail20CallbackQueueManagerEPNS8_10ThreadInfoEEENS2_5list2INS2_5valueIPS8_EENSD_ISA_EEEEEEE3runEv+20)
  native: pc 00000000002a5cbd  /data/app/eu.intermodalics.tango_ros_streamer-1/lib/arm/libnodelet_manager.so
  native: pc 0000000000041823  /system/lib/libc.so (_ZL15__pthread_startPv+30)
  native: pc 0000000000019285  /system/lib/libc.so (__start_thread+6)
```
